# Generated by Django 5.1.1 on 2024-10-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaContatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_nome', models.CharField(default='Sem Nome', max_length=100)),
                ('contato_telefone', models.CharField(default='Sem Telefone', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='agressor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='agressor',
        ),
        migrations.AddField(
            model_name='agressor',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='agressor',
            name='historico_ocorrencia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agressores', to='barbara_app.ocorrencia'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='nome_agressor',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='tipo_crime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='vitima',
            name='estado_atual',
            field=models.TextField(default='Estado atual não informado'),
        ),
        migrations.AddField(
            model_name='vitima',
            name='medida_protetiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vitima',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='rg',
            field=models.CharField(default='0000000000', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='telefone',
            field=models.CharField(default='Sem Telefone', max_length=15),
        ),
        migrations.AlterField(
            model_name='agressor',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agressor',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_ocorrencia',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(blank=True, default='Descrição não informada', null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vitima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='barbara_app.vitima'),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='endereco',
            field=models.TextField(default='Endereço não informado'),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='nome',
            field=models.CharField(default='Sem Nome', max_length=100),
        ),
        migrations.CreateModel(
            name='BotaoPanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_vitima', models.CharField(default='Sem Telefone', max_length=15)),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbara_app.vitima')),
            ],
        ),
        migrations.AddField(
            model_name='vitima',
            name='lista_contatos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='barbara_app.listacontatos'),
        ),
    ]
