# Generated by Django 5.1.1 on 2024-10-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agressor',
            name='ficha_criminal',
            field=models.TextField(blank=True, default='Não informada', null=True),
        ),
    ]
