# Generated by Django 5.1.1 on 2024-10-28 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0002_listacontatos_remove_agressor_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agressor',
            name='historico_ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agressores', to='barbara_app.ocorrencia'),
        ),
    ]
