# Generated by Django 5.1.1 on 2024-10-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0005_alter_agressor_historico_ocorrencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agressor',
            name='historico_ocorrencia',
        ),
    ]
