# Generated by Django 5.1.1 on 2024-10-28 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0006_remove_agressor_historico_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='agressor',
            name='historico_ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbara_app.ocorrencia'),
        ),
    ]
