# Generated by Django 5.1.1 on 2024-10-29 20:01

import barbara_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0010_remove_vitima_idade_vitima_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agressor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agressor',
            name='filhos_vitima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agressor',
            name='mora_com_vitima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agressor',
            name='nome_social',
            field=models.CharField(default='Sem Nome Social Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='agressor',
            name='profissao',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='agressor',
            name='relacao_vitima',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agressor',
            name='sexo',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='agressor',
            name='telefone',
            field=models.CharField(default='Sem Telefone', max_length=15),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='localizacao',
            field=models.TextField(default='Endereço não informado'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='medidas_preventivas',
            field=models.CharField(default='Nao Necessaria', max_length=200),
        ),
        migrations.AddField(
            model_name='vitima',
            name='cidade_nascimento',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='vitima',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vitima',
            name='estado_nascimento',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='vitima',
            name='nome_social',
            field=models.CharField(default='Sem Nome Social Informado', max_length=100),
        ),
        migrations.CreateModel(
            name='Boletim_Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='evidencias/', validators=[barbara_app.models.validate_file_extension])),
                ('agressor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletim_ocorrencia', to='barbara_app.agressor')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_ocorrencia', to='barbara_app.ocorrencia')),
                ('vitima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletim_ocorrencia', to='barbara_app.vitima')),
            ],
        ),
    ]
