# Generated by Django 5.1.1 on 2024-10-29 20:30

import barbara_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0011_agressor_email_agressor_filhos_vitima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_destinatario', models.CharField(max_length=100)),
                ('email_remetente', models.EmailField(default='Denuncia Anonima', max_length=254)),
                ('contato_telefone', models.CharField(default='Sem Telefone', max_length=15)),
                ('nome_remetente', models.CharField(default='Sem Nome', max_length=100)),
                ('nome_destinatario', models.CharField(blank=True, default='Nao Informado', max_length=100, null=True)),
                ('assunto', models.CharField(default='Nao Informado', max_length=100)),
                ('conteudo', models.TextField(default='Não informado')),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos/', validators=[barbara_app.models.validate_file_extension])),
            ],
        ),
    ]
