# Generated by Django 5.1.1 on 2024-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbara_app', '0012_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao', models.CharField(max_length=100)),
                ('nome_destinatario', models.CharField(blank=True, default='Nao Informado', max_length=100, null=True)),
                ('assunto', models.CharField(default='Nao Informado', max_length=100)),
                ('conteudo', models.TextField(default='Não informado')),
                ('email_remetente', models.EmailField(default='Nao Informado', max_length=254)),
                ('telefone_remetente', models.CharField(default='Nao Informado', max_length=15)),
                ('nome_remetente', models.CharField(default='Nao Informado', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='contato_telefone',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefone_remetente',
            field=models.CharField(default='Denuncia Anonima', max_length=15),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='nome_remetente',
            field=models.CharField(default='Denuncia Anonima', max_length=100),
        ),
    ]
